In [2]:
import pandas as pd
import numpy as np

In [4]:
array = np.array([1,2,3])

In [5]:
print(array)

[1 2 3]


# Markdown

In [6]:
array2 = np.array([4,5,6])

In [8]:
array3 = array * array2

In [10]:
print(array,' *')
print(array2)
print('=',array3)

[1 2 3]  *
[4 5 6]
= [ 4 10 18]
