In [2]:
import pandas as pd
import numpy as np

In [3]:
array = np.array([1,2,3])

In [4]:
print(array)

[1 2 3]


# Markdown

In [5]:
array2 = np.array([4,5,6])

In [6]:
array3 = array * array2

In [7]:
print(array,' *')
print(array2)
print('=',array3)

[1 2 3]  *
[4 5 6]
= [ 4 10 18]


## Additional Code

In [9]:
df = pd.DataFrame(array3)
print(df)

    0
0   4
1  10
2  18


In [25]:
df[:1]

0
0  4

In [26]:
print("hello world")

hello world
